# Generated by Django 3.2.19 on 2023-07-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entry identifier', max_length=255, verbose_name='Name')),
                ('notes', models.TextField(blank=True, help_text='Aditional notes', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='EntryKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kind identifier', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='FieldKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kind identifier', max_length=100, verbose_name='Name')),
                ('is_secret', models.BooleanField(default=False, help_text='Defines if value must be encrypted and not displayed by default', verbose_name='Secret')),
                ('is_required', models.BooleanField(default=False, help_text='Defines if at least one element of type is required', verbose_name='Required')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group identifier', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='EntryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Field value', max_length=255, verbose_name='Value')),
                ('entry', models.ForeignKey(help_text='Entry', on_delete=django.db.models.deletion.CASCADE, to='manager.entry', verbose_name='Entry')),
                ('name', models.ForeignKey(help_text='Name', on_delete=django.db.models.deletion.CASCADE, to='manager.fieldkind', verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='group',
            field=models.ForeignKey(help_text='Group folder', on_delete=django.db.models.deletion.CASCADE, to='manager.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='entry',
            name='kind',
            field=models.ForeignKey(blank=True, help_text='Entry kind', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.entrykind', verbose_name='Kind'),
        ),
    ]
