# Generated by Django 3.2.19 on 2023-07-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldkind',
            name='validators',
            field=models.CharField(blank=True, help_text='Comma separated values', max_length=255, null=True, verbose_name='Validators'),
        ),
    ]
